"""Unified executable: contest input.csv to final images and output.csv."""

from __future__ import annotations

import argparse
from pathlib import Path
import sys

import numpy as np

from .backends import NoPaddyDetected
from .contest import (
    ContestOutput,
    build_foreground_roi,
    final_output_path,
    input_image_path,
    output_relative_path,
    read_input_csv,
    write_output_csv,
    compose_contest_image,
)
from .factory import build_extractor
from .rice_weed import RiceWeedClassifier, summarize_prediction


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Create required contest -output.JPG images and output.csv from input.csv."
    )
    parser.add_argument(
        "--input-csv",
        type=Path,
        default=Path("input.csv"),
        help="Contest input CSV; default is input.csv in the current directory.",
    )
    parser.add_argument(
        "--model",
        type=Path,
        required=True,
        help="7-feature joblib rice/weed model generated by the supplied detector/train program.",
    )
    parser.add_argument(
        "--output-csv",
        type=Path,
        default=Path("output.csv"),
        help="Final metadata CSV; default is output.csv alongside input.csv.",
    )
    parser.add_argument("--backend", choices=("auto", "zero-shot", "heuristic"), default="auto")
    parser.add_argument("--device", default="auto")
    parser.add_argument("--grounding-model-id", default="IDEA-Research/grounding-dino-tiny")
    parser.add_argument("--sam-model-id", default="facebook/sam-vit-base")
    parser.add_argument("--box-threshold", type=float, default=0.25)
    parser.add_argument("--text-threshold", type=float, default=0.20)
    parser.add_argument("--classification-batch-size", type=int, default=250_000)
    return parser


def _load_rgb_image(path: Path) -> tuple[object, np.ndarray]:
    try:
        from PIL import Image
    except ModuleNotFoundError as error:
        raise RuntimeError("Pillow is required. Install requirements-paddy-mask-contest.txt.") from error
    with Image.open(path) as opened:
        image = opened.convert("RGB")
    return image, np.asarray(image)


def _save_final_rgb(image: np.ndarray, destination: Path) -> None:
    from PIL import Image

    destination.parent.mkdir(parents=True, exist_ok=True)
    # JPEG is prescribed by the contest; quality/subsampling minimize boundary artifacts.
    Image.fromarray(image, mode="RGB").save(destination, format="JPEG", quality=100, subsampling=0)


def main(argv: list[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    try:
        input_csv = args.input_csv.resolve()
        working_directory = input_csv.parent
        records = read_input_csv(input_csv)
        output_csv = args.output_csv if args.output_csv.is_absolute() else working_directory / args.output_csv
        if output_csv.resolve() == input_csv:
            raise ValueError("output.csv must not overwrite input.csv.")

        classifier = RiceWeedClassifier(args.model, args.classification_batch_size)
        extractor, backend = build_extractor(
            args.backend,
            args.device,
            args.grounding_model_id,
            args.sam_model_id,
            args.box_threshold,
            args.text_threshold,
        )
        outputs: list[ContestOutput] = []
        for record in records:
            image_path = input_image_path(working_directory, record.relative_image_path)
            pil_image, rgb = _load_rgb_image(image_path)
            if pil_image.size != (record.width, record.height):
                raise ValueError(
                    f"{record.relative_image_path} is {pil_image.size[0]}x{pil_image.size[1]}, "
                    f"but input.csv declares {record.width}x{record.height}."
                )
            extraction = extractor.extract(pil_image)
            foreground = build_foreground_roi(rgb, extraction.mask)
            prediction = classifier.predict(rgb, foreground.mask)
            final_rgb = compose_contest_image(foreground, prediction.rice_mask, prediction.weed_mask)
            relative_output = output_relative_path(record.relative_image_path)
            _save_final_rgb(final_rgb, final_output_path(working_directory, record.relative_image_path))
            summary = summarize_prediction(prediction)
            outputs.append(
                ContestOutput(
                    input=record,
                    relative_output_path=relative_output,
                    level=str(summary.level),
                    p=str(summary.plant_pixels),
                    w=str(summary.weed_pixels),
                    r=f"{summary.weed_ratio_percent:.6f}",
                )
            )
            print(
                f"{record.relative_image_path} -> {relative_output} "
                f"[{extraction.backend}; p={summary.plant_pixels}; w={summary.weed_pixels}; "
                f"r={summary.weed_ratio_percent:.2f}%; level={summary.level}]"
            )
        write_output_csv(output_csv, outputs)
        print(f"Created {len(outputs)} final contest image(s) with {backend} background masking: {output_csv}")
        return 0
    except (NoPaddyDetected, OSError, RuntimeError, ValueError) as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
